version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: python3.11-slim.dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=production
    restart: always
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
        "--workers",
        "2",
        "--proxy-headers"
      ]

  dokemon:
    image: productiveops/dokemon:latest
    container_name: dokemon_container
    restart: unless-stopped
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.dokemon.rule=Host(`dokemon.example.com`)'
    #   - 'traefik.http.routers.dokemon.entrypoints=websecure'
    #   - 'traefik.http.routers.dokemon.tls.certresolver=dokemon'
    ports:
      - 9090:9090
    volumes:
      - ./.dokemondata:/data
      - /var/run/docker.sock:/var/run/docker.sock
