version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: always
    # command:
    #   [
    #     "uvicorn",
    #     "main:app",
    #     "--host",
    #     "0.0.0.0",
    #     "--port",
    #     "8001",
    #     "--workers",
    #     "2",
    #     "--proxy-headers"
    #   ]
