# name: Deploy on Docker Hub

# on:
#   push:
#     branches:
#       - master

# env:
#   IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/realworld-example-app
#   DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
#   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

# jobs:
#   build:
#     name: Build Container

#     runs-on: ubuntu-22.04

#     steps:
#       - uses: actions/checkout@v3

#       - name: Build image and publish to registry
#         run: |
#           docker build -t $IMAGE_NAME:latest .
#           echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
#           docker push $IMAGE_NAME:latest

name: Build and Deploy Multi-platform Docker Image

on:
 push:
    branches:
      - master

env:
 IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/realworld-example-app
 DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
 build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Logout from DockerHub
        uses: docker/logout-action@v1
