name: Schemathesis Test Suite

on:
  push:
    branches:
      - test_phase
  pull_request:
    branches:
      - test_phase

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Start containers
      run: docker compose up app -d --build
    
    - uses: schemathesis/action@v1
      with:
        # Your API schema location
        schema: ${{ secrets.API_SCHEMA_URL }}
        # Set your token from secrets
        token: ${{ secrets.SCHEMATHESIS_TOKEN }}

    - name: Stop containers
      if: always()
      run: docker-compose down
