name: Tests on Rye

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Run tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    # services:
    #   postgres:
    #     image: postgres:11.5-alpine
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: postgres
    #     ports:
    #       - 5432:5432
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Rye
          uses: eifinger/setup-rye@v2
          with:
            enable-cache: true

        - name: Set Rye Config
          run: |
            rye config --set-bool behavior.global-python=true
            rye config --set-bool behavior.use-uv=true

        - name: Set up Python ${{ matrix.python-version }}
          run: |
            export PYTHONUNBUFFERED=1
            rye pin ${{ matrix.python-version }}
            rye sync

        - name: Run Pytest if directory exists
          run: |
            if [ -d "./tests/" ]; then
              rye run pytest
            fi